#!/bin/bash

pushd `dirname "$0"`/frontend
elm make src/Main.elm --optimize --output=_build/elm.js && \
 uglifyjs _build/elm.js --compress 'pure_funcs="F2,F3,F4,F5,F6,F7,F8,F9,A2,A3,A4,A5,A6,A7,A8,A9",pure_getters,keep_fargs=false,unsafe_comps,unsafe' | uglifyjs --mangle --output=_build/elm.min.js && \
 cp html/ws.js _build/ws.js && \
 inline-source --compress false --atribute inline --root ./_build html/index.html _build/index.html
